# Generated by Django 4.0.3 on 2022-06-20 07:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sing', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('date_create', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('pfc', models.CharField(max_length=300, null=True)),
                ('compound', models.CharField(max_length=300, null=True)),
                ('ovd', models.BooleanField(null=True)),
                ('shd', models.BooleanField(null=True)),
                ('bd', models.BooleanField(null=True)),
                ('vbd', models.BooleanField(null=True)),
            ],
        ),
    ]
