# Generated by Django 4.0.3 on 2022-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='base',
            field=models.CharField(max_length=5000000, null=True),
        ),
    ]
