# Generated by Django 4.0.3 on 2022-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('carbohydrate', models.IntegerField(null=True)),
                ('fat', models.IntegerField(null=True)),
                ('fiber', models.IntegerField(null=True)),
                ('energy', models.IntegerField(null=True)),
                ('image', models.CharField(max_length=2000, null=True)),
                ('vegan', models.BooleanField(null=True)),
                ('allergens', models.BooleanField(null=True)),
                ('lactose_free', models.BooleanField(null=True)),
                ('sugarless', models.BooleanField(null=True)),
                ('gluten_free', models.BooleanField(null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('ovd', models.BooleanField(null=True)),
                ('shd', models.BooleanField(null=True)),
                ('bd', models.BooleanField(null=True)),
                ('vbd', models.BooleanField(null=True)),
                ('nbd', models.BooleanField(null=True)),
                ('nkd', models.BooleanField(null=True)),
                ('vkd', models.BooleanField(null=True)),
                ('category', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
