# Generated by Django 4.0.3 on 2022-06-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
