# Generated by Django 4.0.3 on 2022-06-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0002_delete_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
