# Generated by Django 4.0.3 on 2022-06-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0003_alter_product_carbohydrate_alter_product_energy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_item',
            new_name='iditem',
        ),
    ]
