# Generated by Django 4.0.3 on 2022-06-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0004_rename_id_item_product_iditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lactose_free',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sugarless',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vegan',
        ),
    ]
