# Generated by Django 4.0.3 on 2022-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0005_forecast_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('compound', models.CharField(max_length=200, null=True)),
                ('pfc', models.CharField(max_length=5000, null=True)),
                ('diet', models.CharField(blank=True, choices=[('ОВД', 'ОВД'), ('ЩД', 'ЩД'), ('БД', 'БД'), ('ВБД', 'ВБД')], help_text='Book availability', max_length=20)),
            ],
        ),
    ]
