# Generated by Django 4.0.3 on 2022-06-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0006_product_allergens_product_carbohydrate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
