# Generated by Django 4.0.3 on 2022-06-24 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0007_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='daily_horoscopes.product')),
            ],
        ),
    ]
