# Generated by Django 4.0.3 on 2022-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0007_alter_menu_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ovd',
            field=models.BooleanField(null=True),
        ),
    ]
