# Generated by Django 4.0.3 on 2022-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0009_alter_product_allergens_alter_product_bd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ovd_sugarless',
            field=models.BooleanField(null=True),
        ),
    ]
