# Generated by Django 4.0.3 on 2022-06-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0010_menu_bd_menu_vbd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='diet',
        ),
    ]
