# Generated by Django 4.0.3 on 2022-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0010_product_ovd_sugarless'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cooking_method',
            field=models.CharField(max_length=7000, null=True),
        ),
    ]
