# Generated by Django 4.0.3 on 2022-06-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0011_remove_menu_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='pfc',
        ),
    ]
