# Generated by Django 4.0.3 on 2022-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0012_remove_menu_compound_remove_menu_pfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
