# Generated by Django 4.0.3 on 2022-06-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0014_alter_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='compound',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='pfc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
